const t=document.querySelector('.menu-toggle');const m=document.querySelector('#menu');function close(){t.setAttribute('aria-expanded','false');m.classList.remove('is-open');}t.addEventListener('click',()=>{const open=t.getAttribute('aria-expanded')!=='true';t.setAttribute('aria-expanded',String(open));m.classList.toggle('is-open',open);});m.addEventListener('click',event=>{if(event.target.closest('a'))close();});document.addEventListener('keydown',event=>{if(event.key==='Escape' && t.getAttribute('aria-expanded')==='true'){close();t.focus();}}); const s=document.querySelector('.about');const h=document.querySelector('.portrait-halo');const rm=window.matchMedia('(prefers-reduced-motion: reduce)');const ds=[];  const D=0.075;const G=0.035;const P=D+G;const R=0.5+G+D/2;const rs=[0,1,2].map(i=>{const radius=R+i*P;const step=2*Math.asin(P/(2*radius));let count=Math.floor(Math.PI/step)+1;if(count % 2===0)count--;return{radius,step,count};});let q=731;function rand(){q=(q*16807)% 2147483647;return(q - 1)/2147483646;}rs.forEach((v,k)=>{for(let i=0;i<v.count;i++){const A=Math.PI/2+(i -(v.count - 1)/2)*v.step;const d=document.createElement('span');d.className='halo-dot';const pet=(ds.length*37+11)%64;d.style.setProperty('--pet-x',`${pet%8*100/7}%`);d.style.setProperty('--pet-y',`${Math.floor(pet/8)*100/7}%`);d.style.left=`${(0.5 - v.radius * Math.cos(A)) * 100 - D * 50}%`;d.style.top=`${(0.5 - v.radius * Math.sin(A)) * 100 - D * 50}%`;h.append(d);ds.push({d,k,i});}});// Scroll drives cubic paths; rotation follows each path tangent.
const petPaths=ds.map(({d},i)=>{const side=i%2?-1:1;return{d,side,lift:(rand()-.5)*.5,bend:(rand()-.5)*.8,delay:rand()*.16,turn:(rand()-.5)*18};});let petsScheduled=false;
function movePets(){petsScheduled=false;const section=s.getBoundingClientRect(),portrait=h.getBoundingClientRect(),progress=Math.max(0,Math.min(1,(innerHeight-section.top)/(innerHeight+section.height*.15)));petPaths.forEach(({d,side,lift,bend,delay,turn})=>{const t=rm.matches?1:Math.max(0,Math.min(1,(progress-delay)/(1-delay))),u=1-t,startX=side*(section.width*.65+portrait.width*.3),startY=lift*portrait.width,c1x=startX*.72,c1y=startY+bend*portrait.width,c2x=-side*portrait.width*.12,c2y=-portrait.width*.2;
const x=u*u*u*startX+3*u*u*t*c1x+3*u*t*t*c2x,y=u*u*u*startY+3*u*u*t*c1y+3*u*t*t*c2y,dx=3*u*u*(c1x-startX)+6*u*t*(c2x-c1x)-3*t*t*c2x,dy=3*u*u*(c1y-startY)+6*u*t*(c2y-c1y)-3*t*t*c2y;let angle=(Math.atan2(dy,dx)-Math.atan2(-c2y,-c2x))*180/Math.PI;angle=((angle+540)%360)-180;
d.style.transform=`translate(${x}px,${y}px) rotate(${angle+turn*u}deg) scale(${.65+.35*t})`;d.style.opacity=rm.matches?1:Math.min(1,t*5);});}
function schedulePets(){if(!petsScheduled){petsScheduled=true;requestAnimationFrame(movePets);}}
window.addEventListener('scroll',schedulePets,{passive:true});window.addEventListener('resize',schedulePets);rm.addEventListener('change',schedulePets);movePets();
const header=document.querySelector('.site-header');let compact=false,scheduled=false;function updateHeader(){scheduled=false;const y=window.scrollY;if(y>180)compact=true;else if(y<40)compact=false;header.classList.toggle('is-compact',compact);}window.addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(updateHeader);}},{passive:true});function measureHeader(){if(compact||m.classList.contains('is-open'))return;document.documentElement.style.setProperty('--floating-header-height',header.getBoundingClientRect().height+'px');}new ResizeObserver(measureHeader).observe(header);measureHeader();updateHeader();const animatedImages=document.querySelectorAll('img[data-animated-src]');if(!rm.matches){function loadAnimation(img){const still=img.src;img.addEventListener('error',()=>{img.src=still;},{once:true});img.loading='lazy';img.fetchPriority='low';img.src=img.dataset.animatedSrc;}if('IntersectionObserver'in window){const animations=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){animations.unobserve(entry.target);loadAnimation(entry.target);}});},{threshold:.12});animatedImages.forEach(img=>animations.observe(img));}else animatedImages.forEach(loadAnimation);}
const footerRing=document.querySelector('.footer-logo-ring');let ringScheduled=false;function rotateFooterRing(){ringScheduled=false;if(rm.matches)return;const footer=document.querySelector('footer').getBoundingClientRect();footerRing.style.transform=`rotate(${(innerHeight-footer.top)*.18}deg)`;}window.addEventListener('scroll',()=>{if(!ringScheduled){ringScheduled=true;requestAnimationFrame(rotateFooterRing);}},{passive:true});window.addEventListener('resize',rotateFooterRing);rm.addEventListener('change',()=>{footerRing.style.transform='none';rotateFooterRing();});rotateFooterRing();

const portraitBlobs=[...document.querySelectorAll('.portrait-blob')];let blobsScheduled=false;function rotatePortraitBlobs(){blobsScheduled=false;portraitBlobs.forEach((blob,i)=>{const b=blob.parentElement.getBoundingClientRect();const progress=Math.max(-1,Math.min(1,(innerHeight/2-b.top-b.height/2)/(innerHeight/2+b.height/2)));blob.style.setProperty('--blob-angle',`${rm.matches?0:progress*6*(i%2?-1:1)}deg`);});}window.addEventListener('scroll',()=>{if(!blobsScheduled){blobsScheduled=true;requestAnimationFrame(rotatePortraitBlobs);}},{passive:true});window.addEventListener('resize',rotatePortraitBlobs);rm.addEventListener('change',rotatePortraitBlobs);rotatePortraitBlobs();

// Seven-column titles; measured line length controls compact heading leading.
const titles=[...document.querySelectorAll('main h1,main h2')],titleMeasure=document.createElement('canvas').getContext('2d');let titleFrame;
function fitTitles(){cancelAnimationFrame(titleFrame);titleFrame=requestAnimationFrame(()=>{titles.forEach(title=>{const wrap=title.closest('.wrap'),grid=getComputedStyle(wrap),gap=parseFloat(grid.columnGap)||parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--gap'))||0,column=(wrap.clientWidth-11*gap)/12;title.style.setProperty('--title-width',`${innerWidth>700?7*column+6*gap:wrap.clientWidth}px`);const parts=[...title.querySelectorAll('.heading-roman,em')];(parts.length?parts:[title]).forEach(part=>{const style=getComputedStyle(part),font=parseFloat(style.fontSize),text=part.textContent.trim();titleMeasure.font=`${style.fontWeight} ${style.fontSize} ${style.fontFamily}`;const width=titleMeasure.measureText(style.textTransform==='uppercase'?text.toUpperCase():text).width+Math.max(0,text.length-1)*(parseFloat(style.letterSpacing)||0);part.style.lineHeight=width/font<=12?'1.02':'1.12';});title.style.lineHeight='1.08';});});}
window.addEventListener('resize',fitTitles,{passive:true});document.fonts.ready.then(fitTitles);fitTitles();
